package HideawayLogger;

public enum OutgoingMessageCodes {
    Pong(2),
    KeepAlivePing(5),
    RequestLocale(7),
    CheckAccountLink(19),
    GooglePlayLogin(20),
    GameCenterLogin(21),
    FacebookLogin(22),
    GuestLogin(23),
    DeleteAvatar(30),
    CreateAvatar(31),
    SelectAvatar(33),
    LinkAccount(38),
    HwReferralToken(70),
    PushMessageToken(80),
    TimeSync(98),
    PlayerLooksUpdate(103),
    ModeratorEffectToggle(104),
    FollowPlayerRequest(105),
    PlayerMoodUpdate(106),
    RequestAvatarStatuses(109),
    PlayerDailyRewardCollect(114),
    PlayerNameChange(115),
    RewardedAdWatched(116),
    ImChatSend(120),
    ImChatRead(121),
    PlayerSetActiveStatus(140),
    PlayerSetLooksStatus(141),
    PlayerIdleAnimation(142),
    PlayerSetAdState(143),
    RelationshipAccept(155),
    RelationshipRequest(156),
    RelationshipDecline(157),
    RelationshipDowngrade(158),
    RelationshipSetType(159),
    RelationshipIgnorePlayer(160),
    RelationshipUnignorePlayer(161),
    PlayerSearch(162),
    PlayerProfileRequest(163),
    HeartPlayer(172),
    StartBuildMode(190),
    SaveMyRoom(191),
    SetMyRoomAccess(192),
    CancelBuildMode(193),
    CreateMyRoom(194),
    DeleteMyRoom(196),
    SpaceEnter(200),
    AvatarMove(202),
    SpaceLeave(205),
    AvatarGesture(206),
    AvatarDirectionTurn(207),
    RoomChatWrite(208),
    RoomChatTyping(209),
    SpaceLockAcquire(210),
    SpaceLockRelease(211),
    AvatarTeleport(212),
    AvatarLoopingGestureStop(213),
    FindMyFriends(214),
    AvatarSetGestureTarget(215),
    AvatarResetGestureTarget(216),
    TwoPlayerGestureInit(218),
    TwoPlayerGestureResponse(219),
    TwoPlayerGestureCancel(220),
    CreateVamos(221),
    JoinVamos(222),
    LeaveVamos(223),
    CancelVamos(225),
    TwoPlayerDominatingGesture(226),
    AchievementsRequest(230),
    AchievementsRewardRequest(232),
    LeaderboardDataRequest(233),
    ChangeMyRoomName(245),
    ChangeMyRoomDescription(246),
    ChangeMyRoomIcon(247),
    RoomSlotPurchase(248),
    LootingStart(251),
    LootBoxOpen(252),
    ShopOfferPurchase(301),
    TargetedOfferPurchase(302),
    ValidateInAppPurchase(304),
    TargetedOfferActivation(305),
    RequestCrafting(307),
    SellItem(311),
    MassClothingPurchase(314),
    FundsHardToSoftConvert(352),
    PlayerProfileMottoValidation(400),
    PlayerProfileTextValidation(401),
    PlayerProfileStickerLayoutValidation(402),
    ModerationReportCreate(650),
    SendFeedback(651),
    Cheat(666),
    PurchaseDailySpins(711),
    Spin(712),
    DailySpin(715),
    AvatarContentEditorPullProducts(800),
    AvatarContentEditorPullClothingSets(801),
    AvatarContentEditorSync(802),
    RiftCreateParty(902),
    RiftJoinParty(903),
    RiftBonusGameResult(908),
    RiftExit(909),
    RiftClaimReward(911),
    RiftRewardPet(914),
    GameTaskRewardsRedeem(950),
    GameTaskModuleViewed(951),
    TutorialTaskCompleted(952),
    SkipTutorial(953),
    SkipTaskModule(954),
    NewsGetAll(1000),
    EventLogging(1001),
    GdprAddRequest(1010),
    GdprCancelRequest(1011),
    GdprDataAvailabilityNotified(1012),
    UseCarpenterBox(1101),
    CollectCarpenterFreeBox(1103),
    CarpenterBuyDefaultBox(1104),
    RoomLayoutSwitch(1150);

    private final int id;
    OutgoingMessageCodes(int id) {
        this.id = id;
    }

    public static String getString(int id) {
        for (OutgoingMessageCodes code : OutgoingMessageCodes.values())
            if (code.id == id)
                return code.toString();

            return Integer.toString(id);
    }
}
